#ifndef CLOCKS_H
#define CLOCKS_H

#include <stdint.h>

#include "rp2350-map.h"
#include "helpers.h"

#define XOSC_CTRL_REG		0
#define XOSC_STATUS_REG		1

#define XOSC_CTRL_ENABLE		((0xfabu) << (12))
#define XOSC_CTRL_DISABLE		((0xd1eu) << (12))
#define XOSC_CTRL_FREQ_RANGE_1_15MHz	((0xaa0u))
#define XOSC_STATUS_STABLE_SHIFT	31
#define XOSC_STATUS_ENABLED_SHIFT	12

#define CLOCKS_CTRL_ENABLE_SHIFT		11
#define CLOCKS_CTRL_AUXSRC_SHIFT		5
#define CLOCKS_CTRL_SRC_SHIFT			0
#define CLOCKS_DIV_INT_SHIFT			16
#define CLOCKS_SELECTED_SHIFT			0

#define CLOCKS_PERIF_CTRL_REG			18
#define CLOCKS_PERIF_DIV_REG			19
#define CLOCKS_PERIF_CTRL_CLK_SYS_AUXSRC	0
#define CLOCKS_PERIF_CTRL_XOSC_AUXSRC		3

#define CLOCKS_HSTX_CTRL_REG			21
#define CLOCKS_HSTX_DIV_REG			22
#define CLOCKS_HSTX_CTRL_CLK_SYS_AUXSRC		0

#define CLOCKS_USB_CTRL_REG			24
#define CLOCKS_USB_DIV_REG			25
#define CLOCKS_USB_CTRL_PLL_USB_AUXSRC		0
#define CLOCKS_USB_CTRL_XOSC_AUXSRC		3

#define CLOCKS_ADC_CTRL_REG			27
#define CLOCKS_ADC_DIV_REG			28
#define CLOCKS_ADC_CTRL_PLL_USB_AUXSRC		0
#define CLOCKS_ADC_CTRL_XOSC_AUXSRC		3

#define CLOCKS_REF_CTRL_REG			12
#define CLOCKS_REF_DIV_REG			13
#define CLOCKS_REF_SELECTED			14
#define CLOCKS_REF_CTRL_XOSC_SRC		2

#define CLOCKS_SYS_CTRL_REG			15
#define CLOCKS_SYS_DIV_REG			16
#define CLOCKS_SYS_SELECTED			17
#define CLOCKS_SYS_CTRL_PLL_SYS_AUXSRC		0
#define CLOCKS_SYS_CTRL_CLK_REF_SRC		0
#define CLOCKS_SYS_CTRL_CLK_SYS_AUX_SRC		1

#define PLL_CS_REG		0
#define PLL_CS_LOCK_SHIFT	31

#define PLL_PWR_REG		1
#define PLL_PWR_PD_SHIFT	0
#define PLL_PWR_POSTDIVPD_SHIFT	3
#define PLL_PWR_VCOPD_SHIFT	5

#define PLL_FBDIV_INT_REG	2

#define PLL_PRIM_REG		3
#define PLL_PRIM_PDIV1_SHIFT	16
#define PLL_PRIM_PDIV2_SHIFT	12

#define MHZ		1000000UL

#define PLL_USB_HZ	(48UL * MHZ)
#define PLL_SYS_HZ	(150UL * MHZ)
#define XOSC_HZ		(12UL * MHZ)

#define CLK_USB		PLL_USB_HZ
#define CLK_USB		PLL_USB_HZ
#define CLK_ADC		PLL_USB_HZ
#define CLK_REF		XOSC_HZ
#define CLK_SYS		PLL_SYS_HZ
#define CLK_PERIF	CLK_SYS
#define CLK_HSTX	CLK_SYS

static inline void xosc_init(void) {
	XOSC_BASE[XOSC_CTRL_REG] = XOSC_CTRL_ENABLE | XOSC_CTRL_FREQ_RANGE_1_15MHz;
	loop_until_bit_is_set(XOSC_BASE[XOSC_STATUS_REG], XOSC_STATUS_STABLE_SHIFT);
}

static inline void set_perif_clock_clk_sys(void) {
	CLOCKS_BASE[CLOCKS_PERIF_CTRL_REG] &= ~BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	delay(10000);
	CLOCKS_BASE[CLOCKS_PERIF_CTRL_REG] =
		CLOCKS_PERIF_CTRL_CLK_SYS_AUXSRC << CLOCKS_CTRL_AUXSRC_SHIFT;
	CLOCKS_BASE[CLOCKS_PERIF_CTRL_REG] |= BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	CLOCKS_BASE[CLOCKS_PERIF_DIV_REG] = 1 << CLOCKS_DIV_INT_SHIFT;
}

static inline void set_hstx_clock_clk_sys(void) {
	CLOCKS_BASE[CLOCKS_HSTX_CTRL_REG] &= ~BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	delay(10000);
	CLOCKS_BASE[CLOCKS_HSTX_CTRL_REG] =
		CLOCKS_HSTX_CTRL_CLK_SYS_AUXSRC << CLOCKS_CTRL_AUXSRC_SHIFT;
	CLOCKS_BASE[CLOCKS_HSTX_CTRL_REG] |= BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	CLOCKS_BASE[CLOCKS_HSTX_DIV_REG] = 1 << CLOCKS_DIV_INT_SHIFT;
}

static inline void set_usb_clock_pll_usb(void) {
	CLOCKS_BASE[CLOCKS_USB_CTRL_REG] &= ~BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	delay(10000);
	CLOCKS_BASE[CLOCKS_USB_CTRL_REG] =
		CLOCKS_USB_CTRL_PLL_USB_AUXSRC << CLOCKS_CTRL_AUXSRC_SHIFT;
	CLOCKS_BASE[CLOCKS_USB_CTRL_REG] |= BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	CLOCKS_BASE[CLOCKS_USB_DIV_REG] = 1 << CLOCKS_DIV_INT_SHIFT;
}

static inline void set_adc_clock_pll_usb(void) {
	CLOCKS_BASE[CLOCKS_ADC_CTRL_REG] &= ~BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	delay(10000);
	CLOCKS_BASE[CLOCKS_ADC_CTRL_REG] =
		CLOCKS_ADC_CTRL_PLL_USB_AUXSRC << CLOCKS_CTRL_AUXSRC_SHIFT;
	CLOCKS_BASE[CLOCKS_ADC_CTRL_REG] |= BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	CLOCKS_BASE[CLOCKS_ADC_DIV_REG] = 1 << CLOCKS_DIV_INT_SHIFT;
}

static inline void set_ref_clock_xosc(void) {
	//uint32_t selected = BIT(CLOCKS_REF_CTRL_XOSC_SRC + CLOCKS_SELECTED_SHIFT);

	CLOCKS_BASE[CLOCKS_REF_CTRL_REG] &= ~BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	delay(10000);
	CLOCKS_BASE[CLOCKS_REF_CTRL_REG] = CLOCKS_REF_CTRL_XOSC_SRC << CLOCKS_CTRL_SRC_SHIFT;
	//loop_until_bit_is_set(CLOCKS_BASE[CLOCKS_REF_SELECTED], selected);
	CLOCKS_BASE[CLOCKS_REF_CTRL_REG] |= BIT(CLOCKS_CTRL_ENABLE_SHIFT);
	CLOCKS_BASE[CLOCKS_REF_DIV_REG] = 1 << CLOCKS_DIV_INT_SHIFT;
}

static inline void set_sys_clock_pll_sys(void) {
	//uint32_t ref_selected = BIT(CLOCKS_SYS_CTRL_CLK_REF_SRC + CLOCKS_SELECTED_SHIFT);
	//uint32_t aux_selected = BIT(CLOCKS_SYS_CTRL_CLK_SYS_AUX_SRC + CLOCKS_SELECTED_SHIFT);

	CLOCKS_BASE[CLOCKS_SYS_CTRL_REG] = CLOCKS_SYS_CTRL_CLK_REF_SRC << CLOCKS_CTRL_SRC_SHIFT;
	//loop_until_bit_is_set(CLOCKS_BASE[CLOCKS_SYS_CTRL], ref_selected);
	CLOCKS_BASE[CLOCKS_SYS_CTRL_REG] =
		CLOCKS_SYS_CTRL_PLL_SYS_AUXSRC << CLOCKS_CTRL_AUXSRC_SHIFT;
	CLOCKS_BASE[CLOCKS_SYS_CTRL_REG] = CLOCKS_SYS_CTRL_CLK_SYS_AUX_SRC << CLOCKS_CTRL_SRC_SHIFT;
	//loop_until_bit_is_set(CLOCKS_BASE[CLOCKS_SYS_CTRL], aux_selected);
	CLOCKS_BASE[CLOCKS_SYS_DIV_REG] = 1 << CLOCKS_DIV_INT_SHIFT;

}

static inline void set_usb_pll(void) {
	PLL_USB_BASE[PLL_CS_REG] = 1; // REFDIV = 1
	PLL_USB_BASE[PLL_FBDIV_INT_REG] = 100; // 12MHz*100 = 1200MHz

	// Power up the PLL
	PLL_USB_BASE[PLL_PWR_REG] &= NBIT(PLL_PWR_PD_SHIFT) & NBIT(PLL_PWR_VCOPD_SHIFT);

	// Wait for PLL to lock
	loop_until_bit_is_set(PLL_USB_BASE[PLL_CS_REG], PLL_CS_LOCK_SHIFT);

	// 1200MHz / (5 * 5) = 48MHz
	PLL_USB_BASE[PLL_PRIM_REG] = (5 << PLL_PRIM_PDIV1_SHIFT) | (5 << PLL_PRIM_PDIV2_SHIFT);

	// Enable PLL output
	PLL_USB_BASE[PLL_PWR_REG] &= NBIT(PLL_PWR_POSTDIVPD_SHIFT);
}

static inline void set_sys_pll(void) {
	PLL_SYS_BASE[PLL_CS_REG] = 1; // REFDIV = 1
	PLL_SYS_BASE[PLL_FBDIV_INT_REG] = 125; // 12MHz*125 = 1500MHz

	// Power up the PLL
	PLL_SYS_BASE[PLL_PWR_REG] &= NBIT(PLL_PWR_PD_SHIFT) & NBIT(PLL_PWR_VCOPD_SHIFT);

	// Wait for PLL to lock
	loop_until_bit_is_set(PLL_SYS_BASE[PLL_CS_REG], PLL_CS_LOCK_SHIFT);

	// 1500MHz / (5 * 2) = 150MHz
	PLL_SYS_BASE[PLL_PRIM_REG] = (5 << PLL_PRIM_PDIV1_SHIFT) | (2 << PLL_PRIM_PDIV2_SHIFT);

	// Enable PLL output
	PLL_SYS_BASE[PLL_PWR_REG] &= NBIT(PLL_PWR_POSTDIVPD_SHIFT);
}

#endif /* CLOCKS_H */
